### ISSUE TITLE
livedemo

### ISSUE THREAD

**Issue by ardianys** [sonnylazuardi/wordchain#1]
bisa minta tolong dibuatin live demo nya gan ? 
biar bisa ngasih contoh ke orang lebih cepat
Trims.

**Comment by sonnylazuardi** [comment]
sebenarnya live demonya sudah ada di github pages bisa diakses di http://sonnylazuardi.github.io/wordchain

**Comment by ardianys** [comment]
ok sip bro

2014-05-07 17:26 GMT+07:00 Sonny Lazuardi notifications@github.com:

> sebenarnya live demonya sudah ada di github pages bisa diakses di
> http://sonnylazuardi.github.io/wordchain
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sonnylazuardi/wordchain/issues/1#issuecomment-42411249
> .

## 

## Ardian Yuli Setyanto

P : 085 643 077 390
S, FB, T : ardianys
W : ardianys.com ilmoe.com http://www.ilmoe.com/

**Comment by ardianys** [comment]
http://sonnylazuardi.github.io/wordchain -> 404 Not Found

Pada 7 Mei 2014 17.27, Ardian Yuli Setyanto ardianys@gmail.com menulis:

> ok sip bro
> 
> 2014-05-07 17:26 GMT+07:00 Sonny Lazuardi notifications@github.com:
> 
> sebenarnya live demonya sudah ada di github pages bisa diakses di
> 
> > http://sonnylazuardi.github.io/wordchain
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/sonnylazuardi/wordchain/issues/1#issuecomment-42411249
> > .
> 
> ## 
> 
> ## Ardian Yuli Setyanto
> 
> P : 085 643 077 390
> S, FB, T : ardianys
> W : ardianys.com ilmoe.com http://www.ilmoe.com/

## 

## Ardian Yuli Setyanto

P : 085 643 077 390
S, FB, T : ardianys
W : ardianys.com ilmoe.com http://www.ilmoe.com/

**Comment by sonnylazuardi** [comment]
ini saya pake browsershot bisa dibuka kok http://browsershots.org/screenshots/48ad111dd18151561f300b583a8dad3e, coba refresh aja mungkin masih kena cache

**Comment by ardianys** [comment]
Sip! mantap bro!

2014-05-07 17:35 GMT+07:00 Sonny Lazuardi notifications@github.com:

> ini saya pake browsershot bisa dibuka kok
> http://browsershots.org/screenshots/48ad111dd18151561f300b583a8dad3e,
> coba refresh aja
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sonnylazuardi/wordchain/issues/1#issuecomment-42411916
> .

## 

## Ardian Yuli Setyanto

P : 085 643 077 390
S, FB, T : ardianys
W : ardianys.com ilmoe.com http://www.ilmoe.com/
