### ISSUE TITLE
Previous error keep appearing

### ISSUE THREAD

**Issue by pveyes** [sonnylazuardi/wordchain#2]
Step to reproduce
1. Write random word that doesn't start with previous last-character
2. Click send
3. Now write the right one
4. Click send
5. Click again on the input without having to write anything

![salah](https://cloud.githubusercontent.com/assets/1614415/2948493/06884ed8-da03-11e3-88f5-cbf6c6df4bf3.png)

**Comment by sonnylazuardi** [comment]
thank you for the review, problem solved

https://github.com/sonnylazuardi/wordchain/commit/65c60432ef78ba6742645833ad3f041d2c1e637f
